In [15]:
import numpy as np
import pandas as pd

import random

In [16]:
from abc import ABC

In [17]:
# Reading the distance matrix file

with open('instance_files/param_dist.csv') as f:
    matrix_size_raw = f.readline().strip().split(',')
    matrix_size = (int(matrix_size_raw[0]), int(matrix_size_raw[1]))

    # dist_matrix = pd.read_csv(f, header=None)
    dist_matrix = pd.read_csv(f, header=None).values

# print(matrix_size)
print(dist_matrix)


[[  0  15  37  75 195 239 149 262 292 675]
 [ 15   0  45  90 210 247 157 270 300 690]
 [ 37  45   0  45 172 202 112 225 255 652]
 [ 75  90  45   0 135 180  95 190 234 630]
 [195 210 172 135   0  60 161  67 112 495]
 [239 247 202 180  60   0 201  37  67 450]
 [149 157 112  95 161 201   0 206 257 634]
 [262 270 225 190  67  37 206   0  76 444]
 [292 300 255 234 112  67 257  76   0 436]
 [675 690 652 630 495 450 634 444 436   0]]


In [18]:
# Reading the distance matrix file

demand_df = pd.read_csv('instance_files/param_demand_5.csv')
print(demand_df)
# print(demand_df.iloc[3]['id']) -> print the id of the 3rd row


   id  orig  dest  amount  price   lw   uw  selected
0   0     0     6      13  10000   62  110         1
1   1     2     3      13  10000  116  164         1
2   2     0     3      30  10000   44   68         1
3   3     0     3      24  10000   73   97         1
4   4     1     3      12  10000  120  192         1


In [19]:
nodes_df = pd.read_csv('instance_files/param_nodes.csv')
print(nodes_df)

   id  type name   long_name
0   0     1   N0       Delta
1   1     1   N1     Euromax
2   2     1   N2        HOME
3   3     1   N3    Moerdijk
4   4     1   N4       Venlo
5   5     1   N5    Duisburg
6   6     1   N6  Willebroek
7   7     1   N7       Neuss
8   8     1   N8    Dortmund
9   9     1   N9   Nuremberg


In [20]:
class Shipper(Agent):
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
    
    def step(self):
        lsp = random.choice(self.model.lsp_agents)
        lsp.receive_request(self)

class LSP(Agent):
    def __init__(self, unique_id, carriers):
        super().__init__(unique_id, carriers)
        self.location = None
        self.route = []

    def receive_request(self, shipper):
        carrier = random.choice(self.model.carrier_agents)
        carrier.handle_request(shipper)

class Carrier(Agent):

    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)

    def handle_request(self, shipper):
        print(f"Carrier {self.unique_id} is sending a truck for Shipper {shipper.unique_id}.")






In [30]:
class LogisticsModel(Model):
    def __init__(self, num_shippers, num_lsps, num_carriers):
        self.num_agents = num_shippers + num_lsps + num_carriers
        self.schedule = RandomActivation(self)

        # Create agents
        self.shipper_agents = [Shipper(i, self) for i in range(num_shippers)]
        for agent in self.shipper_agents:
            self.schedule.add(agent)
        
        self.lsp_agents = [LSP(i + num_shippers, self) for i in range(num_lsps)]
        for agent in self.lsp_agents:
            self.schedule.add(agent)
        
        self.carrier_agents = [Carrier(i + num_lsps + num_shippers, self) for i in range(num_carriers)]
        for agent in self.carrier_agents:
            self.schedule.add(agent)

    def step(self):
        self.schedule.step()

In [31]:
# End flag that will be set when everything is delivered
end_flag = False

# Parameters for the simulation
num_shippers = 1
num_lsps = 2
num_carriers = 4

model = LogisticsModel(num_shippers, num_lsps, num_carriers)

while(not end_flag):
    model.step()



Step 0
Carrier 5 is sending a truck for Shipper 0.
Step 1
Carrier 4 is sending a truck for Shipper 0.
Step 2
Carrier 6 is sending a truck for Shipper 0.
Step 3
Carrier 5 is sending a truck for Shipper 0.
Step 4
Carrier 3 is sending a truck for Shipper 0.
Step 5
Carrier 3 is sending a truck for Shipper 0.
Step 6
Carrier 5 is sending a truck for Shipper 0.
Step 7
Carrier 4 is sending a truck for Shipper 0.
Step 8
Carrier 4 is sending a truck for Shipper 0.
Step 9
Carrier 4 is sending a truck for Shipper 0.


c:\Users\kosyo\AppData\Local\Programs\Python\Python312\Lib\site-packages\mesa\agent.py:52: FutureWarning: The Mesa Model class was not initialized. In the future, you need to explicitly initialize the Model by calling super().__init__() on initialization.
  self.model.register_agent(self)
